version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    command: mongod --smallfiles --logpath=/dev/null
  adminmongo:
      container_name: adminmongo
      image: mrvautin/adminmongo
      links: ['mongodb:mongodb']
      ports: ['1234:1234']
      environment:
        - PORT=1234
        - HOST=0.0.0.0
        - CONN_NAME=mongodb
        - DB_USERNAME=jupyter
        - DB_PASSWORD=jupyter
        - DB_HOST=mongodb
        - DB_NAME=assignment-2
  jupyter:
    container_name: jupyter
    image: jupyter/datascience-notebook:latest
    ports: ['8888:8888']
    command: start.sh jupyter notebook --NotebookApp.token=''
    volumes:
      - ./:/home/jovyan/work
  
volumes:
  dbdata:
